chore: upgrade Prettier and run on full repo
actions/setup-node pull request #394
Opened 2021-12-30 17:15 UTC by nschonni

**Description:**

- Move Prettier 1 -> to support `.` glob and built-in parsers
- Move whitespace settings to EditorConfig that Prettier reads
- Expand glob to run on all non-generated files

**Related issue:**
Add link to the related issue.

**Check list:**

- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

2021-12-31 17:03 UTC, nschonni commented
@oscard0m probably easier to review this with the "whitespace ignore" option

2022-01-06 12:19 UTC, dmitry-shibanov commented
Hello @nschonni. Thank you for your pull request. We'll investigate it.

2022-02-02 22:20 UTC, lordt4ever commented
No £

2022-02-09 14:46 UTC, Burkay5441 approved these changes

2022-02-09 14:47 UTC, Burkay5441 approved these changes

2022-03-09 16:20 UTC, Shutch748 requested changes
Doesn't belong to them

2026-07-14 11:43 UTC, v-gowridurgad commented
Hi @nschonni, thanks for your contribution! Prettier has already been upgraded to ^3.8.4, so the changes proposed in this PR are already included. We'll be closing this PR as it is already addressed.

2026-07-14 11:43 UTC, closed without merging