README.md: Encourage testing on current Node.js
actions/setup-node pull request #533
Opened 2022-06-30 10:51 UTC by cclauss

**Description:**
Encourage testing on current Node.js

**Related issue:**
in alignment with https://nodejs.org/en/about/releases

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

2022-07-05 15:49 UTC, IvanZosimov requested changes
Hi, @cclauss 👋 Thank you for your suggestion! Could you please change version 18 to 16 (16 is LTS now) to make the file more consistent?

2022-07-05 15:49 UTC, IvanZosimov commented on README.md
> +    node-version: 18
```suggestion
    node-version: 16
```

2022-07-05 15:49 UTC, IvanZosimov commented on README.md
> +    node-version: 18
```suggestion
    node-version: 16
```

2022-07-06 07:29 UTC, marko-zivic-93 approved these changes

2022-07-07 12:53 UTC, merged