Pass the token input through on GHES
actions/setup-node pull request #595
Opened 2022-10-17 10:48 UTC by dmitry-shibanov

**Description:**
In scope of this pull request we make available to pass GitHub token on GHES.

**Related issue:**

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

2022-10-17 11:20 UTC, marko-zivic-93 approved these changes

2022-10-17 13:07 UTC, IvanZosimov approved these changes

2022-10-17 13:41 UTC, vsafonkin approved these changes

2022-10-21 20:36 UTC, brcrista requested changes
This also needs to the change to `action.yml` here: https://github.com/actions/setup-python/pull/443/files

On GHES, this will start using `GITHUB_TOKEN` ([the default value for the `token` input](https://github.com/actions/setup-node/blob/788c6ccbd0d6bddb637da16397c675d9e1c6f93c/action.yml#L23)) to make calls to github.com.  But, the GHES token isn't valid on github.com.

2022-10-26 13:25 UTC, brcrista approved these changes

2022-10-27 06:05 UTC, marko-zivic-93 approved these changes

2022-11-02 11:24 UTC, merged